#!/bin/bash
echo "Testing Idle for 1 minute. Press Ctrl+c when 1 minute done!"
nvidia-smi --query-gpu=timestamp,name,utilization.gpu,utilization.memory,memory.used,memory.free,power.draw --format=csv -l 1 -f gpu_idle.csv && echo "gpu_idle.csv written to file."
echo "Testing full power run (CPU+GPU) for 1 minute. Press Ctrl+c when 1 minute done!"
./gpu_burn 60 & stress --cpu 16 --io 4 --vm 2 --vm-bytes 128M --timeout 60 & nvidia-smi --query-gpu=timestamp,name,utilization.gpu,utilization.memory,memory.used,memory.free,power.draw --format=csv -l 1 -f gpu_high.csv  && echo "gpu_high.csv written to file."
echo "Tests complete, getting system info..."
lsb_release -a > os-info.txt && echo "Wrote os-info.txt to file"
lscpu > cpu-info.txt && echo "Wrote cpu-info.txt to file"
lshw > hw-info.txt && echo "Wrote hw-info.txt to file"
echo "Done!"
